server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/agsr?currentSchema=agsr
    username: agsr
    password: 12345678
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      transaction-isolation: TRANSACTION_READ_COMMITTED
      auto-commit: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    open-in-view: false
statistics:
  token: bbdda530-5558-4588-8ab9-5dcda6bc4faa
sensor:
  service:
    url: "http://localhost:8080/statistics"

