spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agsr?currentSchema=agsr
    username: agsr
    password: 12345678
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      transaction-isolation: TRANSACTION_READ_COMMITTED
      auto-commit: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    open-in-view: false
authentication:
  token:
    secretKey: mh141qF92H53gv4r6vzwatioEnM11Od1i2U46fjOTsk=
statistics:
  token: bbdda530-5558-4588-8ab9-5dcda6bc4faa
